### PR TITLE
Exception rethrown upwards

### PR DESCRIPTION
**Pull request by CesarCoelho**
Fixes this issue:
https://github.com/esa/CCSDS_MO_TRANS/issues/12

### CODE REVIEW

**Review by SamCooper — CHANGES_REQUESTED** [review]
Please add a comment at line 150 i.e.e not a null for the text.

To rethrow an exception you just do at line 505:

throw ex;

You don't need to create a new exception at that will lose the original context.

**Comment by gbonnefille** [comment]
Why not rethrowing the exception in the getElementCount?

I suspect there will be a lot of impact, but it seems better to inform the caller that the information was not computed. With such a change, the caller will continue its processing and probably fail later due to missing elements. Such situation can complexify the investigation on error, even if the logbook contains the relevant error.

**Comment by SamCooper** [comment]
Because that would mean changing the MAL Java API which is a little more involved.

But you could add a RID on the MAL Java to that effect

**Comment by CesarCoelho** [comment]
Done

**Review by SamCooper — APPROVED** [review]

**Pull request merged**
